version: "3"

tasks:
  build-pr:
    - gh pr checkout {{.CLI_ARGS}}
    - task build

  build:
    deps: [ generate ]
    cmds:
      - go build -o build/qatarina

  install-tools:
    cmds:
      - go install github.com/swaggo/swag/v2/cmd/swag@v2.0.0-rc4
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/mitchellh/gox@latest

  install:
    cmds:
      - go mod tidy
      - cd ui && npm install
      - cd ui && npm run build

  migrate:
    cmds:
      - go run main.go migrate

  generate:
    cmds:
      - sqlc generate
      - swag init --v3.1
      - cd ui && npm run gen:api

  dev-ui:
    cmd: cd ui && npm run dev

  dev:
    cmds:
      - cd ui && npm run build
      - go run main.go server

  dist:
    deps: [generate]
    cmds:
      - mkdir -p build
      - cd ui && npm run build
      - gox -ldflags="-X 'github.com/golang-malawi/qatarina/internal/version/version.Version=$(git describe  --tags --candidates 1)'" -osarch="linux/amd64" -output ./build/qatarina_linux_amd64
      - gox -ldflags="-X 'github.com/golang-malawi/qatarina/internal/version/version.Version=$(git describe  --tags --candidates 1)'" -osarch="linux/arm64" -output ./build/qatarina_linux_arm64
