// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/projects": {
            "get": {
                "description": "List Projects available on the platform",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "List Projects available on the platform",
                "operationId": "ListProject",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create a Project",
                "operationId": "CreateProject",
                "parameters": [
                    {
                        "description": "Project Creation data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/import": {
            "post": {
                "description": "Import Projects from some source",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Import Projects from some source",
                "operationId": "ImportProject",
                "parameters": [
                    {
                        "description": "Import Specification",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/query": {
            "get": {
                "description": "Search for a Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Search for a Project",
                "operationId": "SearchProjects",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{projectID}": {
            "get": {
                "description": "Get a single Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get a single Project",
                "operationId": "GetOneProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Update a Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Update a Project",
                "operationId": "UpdateProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Project Update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Project",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Delete a Project",
                "operationId": "DeleteProject",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{projectID}/test-cases": {
            "get": {
                "description": "Get a single Project's test plans",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get a single Project's test plans",
                "operationId": "GetProjectTestPlans",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/projects/{projectID}/test-runs": {
            "get": {
                "description": "Get a single Project's test runs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get a single Project's test runs",
                "operationId": "GetProjectTestRuns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-cases": {
            "get": {
                "description": "List Test Cases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "List Test Cases",
                "operationId": "ListTestCases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Test Case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "Create a new Test Case",
                "operationId": "CreateTestCase",
                "parameters": [
                    {
                        "description": "Create Test Case data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-cases/bulk": {
            "post": {
                "description": "Create multiple Test Cases at once",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "Create multiple Test Cases at once",
                "operationId": "BulkCreateTestCases",
                "parameters": [
                    {
                        "description": "Bulk Create Test Case data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-cases/query": {
            "get": {
                "description": "Search for Test Cases",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "Search for Test Cases",
                "operationId": "SearchTestCases",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-cases/{testCaseID}": {
            "get": {
                "description": "Get a single Test Case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "Get a single Test Case",
                "operationId": "GetOneTestCase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Case ID",
                        "name": "testCaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Update a Test Case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "Update a Test Case",
                "operationId": "UpdateTestCase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Case ID",
                        "name": "testCaseID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test Case update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a test case",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-cases"
                ],
                "summary": "Delete a test case",
                "operationId": "DeleteTestCase",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Case ID",
                        "name": "testCaseID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-plans": {
            "get": {
                "description": "Search all Test Plans",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-plans"
                ],
                "summary": "Search all Test Plans",
                "operationId": "SearchTestPlans",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Test Plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-plans"
                ],
                "summary": "Create a new Test Plan",
                "operationId": "CreateTestPlan",
                "parameters": [
                    {
                        "description": "Create Test plan data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-plans/{testPlanID}": {
            "get": {
                "description": "Get one Test Plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-plans"
                ],
                "summary": "Get one Test Plan",
                "operationId": "GetOneTestPlan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Plan ID",
                        "name": "testPlanID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Update a Test Plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-plans"
                ],
                "summary": "Update a Test Plan",
                "operationId": "UpdateTestPlan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Plan ID",
                        "name": "testPlanID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test Plan data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Test Plan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-plans"
                ],
                "summary": "Delete a Test Plan",
                "operationId": "DeleteTestPlan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Plan ID",
                        "name": "testPlanID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-runs": {
            "get": {
                "description": "List Test Runs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "List Test Runs",
                "operationId": "ListTestRuns",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new Test Run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "Create a new Test Run",
                "operationId": "CreateTestRun",
                "parameters": [
                    {
                        "description": "Test Run data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-runs/query": {
            "get": {
                "description": "Search for Test Runs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "Search for Test Runs",
                "operationId": "SearchTestRuns",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-runs/{testRunID}": {
            "get": {
                "description": "Get one Test Run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "Get one Test Run",
                "operationId": "GetOneTestRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Run ID",
                        "name": "testRunID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Update a Test Run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "Update a Test Run",
                "operationId": "UpdateTestRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Run ID",
                        "name": "testRunID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test Run update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a Test Run",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "Delete a Test Run",
                "operationId": "DeleteTestRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Run ID",
                        "name": "testRunID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/test-runs/{testRunID}/commit": {
            "post": {
                "description": "Mark a Test Run as committed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test-runs"
                ],
                "summary": "Mark a Test Run as committed",
                "operationId": "CommitTestRun",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Test Run ID",
                        "name": "testRunID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Test Run update data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/testers": {
            "get": {
                "description": "List all Testers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testers"
                ],
                "summary": "List all Testers",
                "operationId": "ListTesters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/testers.query": {
            "get": {
                "description": "Search all Testers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testers"
                ],
                "summary": "Search all Testers",
                "operationId": "SearchTesters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/testers/invite/{email}": {
            "post": {
                "description": "Invite a tester by Email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testers"
                ],
                "summary": "Invite a tester by Email",
                "operationId": "InviteTester",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email of tester",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Invite data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/testers/{testerID}": {
            "get": {
                "description": "Get a Tester by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testers"
                ],
                "summary": "Get a Tester by ID",
                "operationId": "GetOneTester",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tester ID",
                        "name": "testerID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "List all Users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List all Users",
                "operationId": "ListUsers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new User",
                "operationId": "CreateUser",
                "parameters": [
                    {
                        "description": "User data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/users/invite/{email}": {
            "post": {
                "description": "Invite a User by email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Invite a User by email",
                "operationId": "InviteUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's email",
                        "name": "email",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User invite data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/users/query": {
            "get": {
                "description": "Search all Users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Search all Users",
                "operationId": "SearchUsers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{userID}": {
            "get": {
                "description": "Get one User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get one User",
                "operationId": "GetOneUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "post": {
                "description": "Update a User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update a User",
                "operationId": "UpdateUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {}
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user",
                "operationId": "DeleteUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/problemdetail.ProblemDetail"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "problemdetail.ProblemDetail": {
            "type": "object",
            "properties": {
                "context": {},
                "detail": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
